### ISSUE TITLE
first issues

### ISSUE THREAD

**Issue by KarinSV** [staffanosp/foundations-site#1]
1) `<title>Document</title>` I think, why not add some more informative title. I mean, I would like understand what about your website.
2) I think there's a better way to do some semantics and comments before every block/box. For example, you can add <header> and <footer> and etc. 
3) Great job with flexboxes. It works so smooth.
4) I didn't find <img> element within your html file, but I see img folder with several images. I think there's a better way to add img folder only if you use that on your website. But maybe you would like add to your website images late.

**Comment by staffanosp** [comment]
Thank you for your feedback 🙏🏻
